"""choices unique constraint

Revision ID: 06d864dd01bd
Revises: 480faef1d741
Create Date: 2024-07-31 21:33:38.714285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d864dd01bd'
down_revision: Union[str, None] = '480faef1d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'choices', ['scene_id', 'next_scene_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'choices', type_='unique')
    # ### end Alembic commands ###
