"""img field

Revision ID: 46ea7b768d97
Revises: ff8e0f38ad7a
Create Date: 2024-09-26 22:54:51.435305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ea7b768d97'
down_revision: Union[str, None] = 'ff8e0f38ad7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('img', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('img', sa.String(), nullable=True))
    # TODO: delete these
    op.execute(
        "UPDATE scenes SET img = '{}' WHERE img IS NULL".format("/staticfiles/story_img.jpg")
    )
    op.execute(
        "UPDATE stories SET img = '{}' WHERE img IS NULL".format("/staticfiles/story_img.jpg")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'img')
    op.drop_column('scenes', 'img')
    # ### end Alembic commands ###
