"""slug field for scenes model

Revision ID: 79313a597572
Revises: 0a287a6fecfa
Create Date: 2024-07-31 00:35:27.968621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79313a597572'
down_revision: Union[str, None] = '0a287a6fecfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('slug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'slug')
    # ### end Alembic commands ###
