"""game_id to story_id

Revision ID: a4d2b89733b2
Revises: 79313a597572
Create Date: 2024-07-31 01:23:29.619752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d2b89733b2'
down_revision: Union[str, None] = '79313a597572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('story_id', sa.Integer(), nullable=True))
    op.drop_constraint('scenes_game_id_fkey', 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'stories', ['story_id'], ['id'])
    op.drop_column('scenes', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key('scenes_game_id_fkey', 'scenes', 'stories', ['game_id'], ['id'])
    op.drop_column('scenes', 'story_id')
    # ### end Alembic commands ###
