"""categories

Revision ID: bc53a590d0f6
Revises: 46ea7b768d97
Create Date: 2024-11-09 02:42:39.577743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'bc53a590d0f6'
down_revision: Union[str, None] = '46ea7b768d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_types = ENUM('ADMIN', 'AUTHOR', 'USER', name='usertypes')
    user_types.create(op.get_bind())
    op.create_table('categories',
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True, unique=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('users', sa.Column('user_type', sa.Enum('ADMIN', 'USER', 'AUTHOR', name='usertypes'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    user_types = ENUM('ADMIN', 'AUTHOR', 'USER', name='usertypes')
    user_types.drop(op.get_bind())
    # ### end Alembic commands ###
