"""story categories

Revision ID: ce9fa99e9a70
Revises: bc53a590d0f6
Create Date: 2024-11-09 03:17:40.408932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9fa99e9a70'
down_revision: Union[str, None] = 'bc53a590d0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storycategories',
    sa.Column('story_slug', sa.String(), nullable=True),
    sa.Column('category_slug', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_slug'], ['categories.slug'], ),
    sa.ForeignKeyConstraint(['story_slug'], ['stories.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storycategories_id'), 'storycategories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storycategories_id'), table_name='storycategories')
    op.drop_table('storycategories')
    # ### end Alembic commands ###
