"""story owner

Revision ID: e33d9d4cd65e
Revises: f7001f072a98
Create Date: 2024-07-31 00:11:13.572902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33d9d4cd65e'
down_revision: Union[str, None] = 'f7001f072a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stories', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'owner_id')
    # ### end Alembic commands ###
