"""scene type

Revision ID: ff8e0f38ad7a
Revises: 56bf12bf424f
Create Date: 2024-09-25 21:40:13.660821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'ff8e0f38ad7a'
down_revision: Union[str, None] = '56bf12bf424f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    scene_types = ENUM('BEGINNING', 'ENDING', 'DEFAULT', name='scenetypes')
    scene_types.create(op.get_bind())
    op.add_column('scenes', sa.Column('type', sa.Enum('BEGINNING', 'ENDING', 'DEFAULT', name='scenetypes'), nullable=True))
    op.execute(
        "UPDATE scenes SET type = '{}' WHERE type IS NULL".format("DEFAULT")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'type')
    scene_types = ENUM('BEGINNING', 'ENDING', 'DEFAULT', name='scenetypes')
    scene_types.drop(op.get_bind())
    # ### end Alembic commands ###
